// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
// ...
// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuTBvJEv_9nRT3aFSF5RnZn4e00rdokms',
    appId: '1:1097168827280:web:8c281039d83b013c323915',
    messagingSenderId: '1097168827280',
    projectId: 'tellmeastory-a76c7',
    authDomain: 'tellmeastory-a76c7.firebaseapp.com',
    storageBucket: 'tellmeastory-a76c7.appspot.com',
    measurementId: 'G-19314ZFCDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJFjNdHd79gG3R6I8x7VkQ3DRxdfmpABY',
    appId: '1:1097168827280:android:6b1abc6babb200a5323915',
    messagingSenderId: '1097168827280',
    projectId: 'tellmeastory-a76c7',
    storageBucket: 'tellmeastory-a76c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANrcc0T8irpavedjo1tVh3T-IEWFX3mBA',
    appId: '1:1097168827280:ios:dbb731155bce7ddd323915',
    messagingSenderId: '1097168827280',
    projectId: 'tellmeastory-a76c7',
    storageBucket: 'tellmeastory-a76c7.appspot.com',
    iosClientId: '1097168827280-fajn3ipl25trl88r7ki76f271toisjhf.apps.googleusercontent.com',
    iosBundleId: 'space.transform3.speakchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANrcc0T8irpavedjo1tVh3T-IEWFX3mBA',
    appId: '1:1097168827280:ios:3f334855378b2fe0323915',
    messagingSenderId: '1097168827280',
    projectId: 'tellmeastory-a76c7',
    storageBucket: 'tellmeastory-a76c7.appspot.com',
    iosClientId: '1097168827280-ctj7aockq8qjo1obr1f1i1jj2bep9lar.apps.googleusercontent.com',
    iosBundleId: 'space.transform3.speakChat',
  );
}
